### ISSUE TITLE
Request: Output in plain Text format

### ISSUE THREAD

**Issue by DustofShadows** [Jessuhh/discord-timestamps-flowlauncher-plugin#9]
Hi there 👋
Thank you for your cool plugin! I really like it! 
I find it very useful to look up a time or a date; but I don't really use the Discord Timestamp Syntax (actually I don't know which usecases I would have for it).
Yet, I would love to be able to copy the outuput as it is displayed in the better-readable plain text instead of the discord timestamp format. Would this be possible to integrate in this plugin? I would absolutely love that.

All the best,
Leo

**Comment by Jessuhh** [comment]
Hello Leo,

This plugin is made to generate these timestamps for discord specifically. Their use case is to be able to communicate a set point in time with people in different time zones. Ideal for scheduling international events for example. On what platform are you sharing your timestamps? It might have a similar feature.

Personally I have no intent on creating the requested feature, sorry. I feel like it's out of scope for this discord plugin. You could consider creating your own flowlauncher plugin. If you do, feel free to take my code as an example. If you have any other questions, feel free to reach out!

**Comment by Jessuhh** [comment]
Perhaps this plugin meets your needs? https://github.com/Garulf/Flow.Launcher.Plugin.Timestamp

**Comment by DustofShadows** [comment]
The Timestamp plugin misses some nice functionality which yours has. And I can see the point of using Unix timestamps now (I did not know about them). :)
I was using your plugin as more of a plain text lookup for dates and times for scheduling or writing emails.

If this is fine that I can adapt your code, I would try to provide an alternative to your Unix output as another FlowLauncher plugin. Being able to have both at hand makes sense to me. 😇

**Comment by Jessuhh** [comment]
> If this is fine that I can adapt your code, I would try to provide an alternative to your Unix output as another FlowLauncher plugin. Being able to have both at hand makes sense to me. 😇

Having thought about it a little bit now, it doesn't seem too weird to also offer plaintext alternatives to copy in the output of the plugin. Feel free to make a pull request for this plugin. Else I'll try to realize such a feature in the near future. Any suggestions about which formats you would like to get from the plugin?

**Comment by Jessuhh** [comment]
https://github.com/DustofShadows/Smart-Timestamps-FlowLauncher-Plugin
